       IDENTIFICATION DIVISION.
       PROGRAM-ID. RRMBS196.
      *
      * Generated COBOL program
      * by RRMAC Associates LLC on 2 Sep 2016 at 11:56:13
      *
      *                                         
      * Added by Robin and Bill 1/5/19          
      * Modified by Robin on 1/7/19 part 5            
      
       ENVIRONMENT DIVISION.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      * NO-DB2
      * NO-DB2
           COPY
            RRMBC196.

       PROCEDURE DIVISION.
      * NO-DB2
      * NO-DB2
      * NO-DB2
           MOVE INCL-11-A TO INCL-21-A.
      * NO-CICS
      * NO-CICS
      * NO-CICS
           GOBACK.
      *End of program RRMBS196.